### ISSUE TITLE
Modeling of the database

### ISSUE THREAD

**Issue by Houssem-Guemer** [Houssem-Guemer/Scout-Project#5]
make models of all our users to start building the database : 
captains;
travelers;
and thats all for now ;) .

**Comment by hzerrad** [comment]
This is already modelled in the database. If you check the ERD you'd find a scouts table which represents any signed-up traveller (and eventually a captain because both require the same specifiactions and hence same business data). Moreover, if this scout is a Captain, a new record in captains table is added with his id and extra needed information (such as role, aproval, etc...)
